#ALL SCRIPTS
fivemonth_soupx <- CreateSeuratObject(counts = fivemonthcounts, project = "A", min.cells = 3, min.features = 200)
fivemonth_soupx[["percent.mt"]] <- PercentageFeatureSet(fivemonth_soupx, pattern = "^MT-")

VlnPlot(fivemonth_soupx, features = c("nFeature_RNA", "nCount_RNA"), ncol = 2)
featurescatterplot <- FeatureScatter(fivemonth_soupx, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
plot(featurescatterplot)
fivemonth_soupx <- subset(fivemonth_soupx, subset = nFeature_RNA > 200 & nFeature_RNA < 3200)
fivemonth_soupx <- NormalizeData(fivemonth_soupx)
fivemonth_soupx <- FindVariableFeatures(fivemonth_soupx, selection.method = "vst", nfeatures = 2000)
top10 <- head(VariableFeatures(fivemonth_soupx), 10)
plot1variable <- VariableFeaturePlot(fivemonth_soupx)
plot2variable <- LabelPoints(plot = plot1variable, points = top10, repel = TRUE)
CombinePlots(plots = list(plot1variable, plot2variable))
all.genes5mo <- rownames(fivemonth_soupx)
fivemonth_soupx <- ScaleData(fivemonth_soupx, features = all.genes5mo)
fivemonth_soupx <- RunPCA(fivemonth_soupx, features = VariableFeatures(object = fivemonth_soupx))
VizDimLoadings(fivemonth_soupx, dims = 1:2, reduction = "pca")
DimPlot(fivemonth_soupx, reduction = "pca")
DimHeatmap(fivemonth_soupx, dims = 1:15, cells = 500, balanced = TRUE)
fivemonth_soupx <- FindNeighbors(fivemonth_soupx, dims = 1:12)
fivemonth_soupx <- FindClusters(fivemonth_soupx, resolution = 0.5)
fivemonth_soupx <- RunUMAP(fivemonth_soupx, dims = 1:12)
DimPlot(fivemonth_soupx, reduction = "umap", label = TRUE)
#TwentyfourMonth
twentyfour_soupx <- CreateSeuratObject(counts = twentyfourcounts, project = "B", min.cells = 3, min.features = 200)
VlnPlot(twentyfour_soupx, features = c("nFeature_RNA", "nCount_RNA"), ncol = 2)
featurescatterplot <- FeatureScatter(twentyfour_soupx, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
plot(featurescatterplot)
twentyfour_soupx <-  subset(twentyfour_soupx, subset = nFeature_RNA > 200 & nFeature_RNA < 4000) 
twentyfour_soupx <- NormalizeData(twentyfour_soupx)
twentyfour_soupx <- FindVariableFeatures(twentyfour_soupx, selection.method = "vst", nfeatures = 2000)
top10 <- head(VariableFeatures(twentyfour_soupx), 10)
plot1variable <- VariableFeaturePlot(twentyfour_soupx)
plot2variable <- LabelPoints(plot = plot1variable, points = top10, repel = TRUE)
CombinePlots(plots = list(plot1variable, plot2variable))
all.genes5mo <- rownames(twentyfour_soupx)
twentyfour_soupx <- ScaleData(twentyfour_soupx, features = all.genes5mo)
twentyfour_soupx <- RunPCA(twentyfour_soupx, features = VariableFeatures(object = twentyfour_soupx))
VizDimLoadings(twentyfour_soupx, dims = 1:2, reduction = "pca")
DimPlot(twentyfour_soupx, reduction = "pca")
DimHeatmap(twentyfour_soupx, dims = 1:15, cells = 500, balanced = TRUE)
twentyfour_soupx <- FindNeighbors(twentyfour_soupx, dims = 1:15)
twentyfour_soupx <- FindClusters(twentyfour_soupx, resolution = 0.5)
twentyfour_soupx <- RunUMAP(twentyfour_soupx, dims = 1:15)
twentyfour_soupx <- RenameIdents(twentyfour_soupx, "0" = "Type IIb Myonuclei", "1" = "Type IIx Myonuclei", "2" = "Type IIb Myonuclei", "3" = "Type IIx Myonuclei", "4" = "FAPs", "5" = "Smooth Muscle", "6" = "Endothelial Cells", "7" = "Musculotendinous Junction", "8" = "Satellite Cells", "9" = "Immune Cells", "10" = "Smooth Muscle", "11" = "Endothelial Cells", "12" = "Neuromuscular Junction", "13" = "Schwann Cells", "14" = "Unidentified")
DimPlot(twentyfour_soupx, reduction = "umap", label = TRUE)
#Thirty
thirty_soupx <- CreateSeuratObject(counts = thirtycounts, project = "C", min.cells = 3, min.features = 200)
VlnPlot(thirty_soupx, features = c("nFeature_RNA", "nCount_RNA"), ncol = 2)
featurescatterplot <- FeatureScatter(thirty_soupx, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
plot(featurescatterplot)
thirty_soupx <- subset(thirty_soupx, subset = nFeature_RNA > 200 & nFeature_RNA < 4000)
thirty_soupx <- NormalizeData(thirty_soupx)
thirty_soupx <- FindVariableFeatures(thirty_soupx, selection.method = "vst", nfeatures = 2000)
top10 <- head(VariableFeatures(thirty_soupx), 10)
plot1variable <- VariableFeaturePlot(thirty_soupx)
plot2variable <- LabelPoints(plot = plot1variable, points = top10, repel = TRUE)
CombinePlots(plots = list(plot1variable, plot2variable))
all.genes5mo <- rownames(thirty_soupx)
thirty_soupx <- ScaleData(thirty_soupx, features = all.genes5mo)
thirty_soupx <- RunPCA(thirty_soupx, features = VariableFeatures(object = thirty_soupx))
VizDimLoadings(thirty_soupx, dims = 1:2, reduction = "pca")
DimPlot(thirty_soupx, reduction = "pca")
DimHeatmap(thirty_soupx, dims = 1:15, cells = 500, balanced = TRUE)
thirty_soupx <- FindNeighbors(thirty_soupx, dims = 1:20)
thirty_soupx <- FindClusters(thirty_soupx, resolution = 0.5)
thirty_soupx <- RunUMAP(thirty_soupx, dims = 1:20)
DimPlot(thirty_soupx, reduction = "umap", label = TRUE)
#p10 soupx
p10_soupx <- CreateSeuratObject(counts = p10_counts, project = "p10", min.cells = 3, min.features = 200)
VlnPlot(p10_soupx, features = c("nFeature_RNA", "nCount_RNA"), ncol = 2)
featurescatterplot <- FeatureScatter(p10_soupx, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
plot(featurescatterplot)
p10_soupx <- subset(p10_soupx, subset = nFeature_RNA > 200 & nFeature_RNA < 4200)
p10_soupx <- NormalizeData(p10_soupx)
p10_soupx <- FindVariableFeatures(p10_soupx, selection.method = "vst", nfeatures = 2000)
top10 <- head(VariableFeatures(p10_soupx), 10)
plot1variable <- VariableFeaturePlot(p10_soupx)
plot2variable <- LabelPoints(plot = plot1variable, points = top10, repel = TRUE)
CombinePlots(plots = list(plot1variable, plot2variable))
all.genes5mo <- rownames(p10_soupx)
p10_soupx <- ScaleData(p10_soupx, features = all.genes5mo)
p10_soupx <- RunPCA(p10_soupx, features = VariableFeatures(object = p10_soupx))
VizDimLoadings(p10_soupx, dims = 1:2, reduction = "pca")
DimPlot(p10_soupx, reduction = "pca")
DimHeatmap(p10_soupx, dims = 1:15, cells = 500, balanced = TRUE)
p10_soupx <- FindNeighbors(p10_soupx, dims = 1:20)
p10_soupx <- FindClusters(p10_soupx, resolution = 0.5)
p10_soupx <- RunUMAP(p10_soupx, dims = 1:20)
DimPlot(p10_soupx, reduction = "umap", label = TRUE)
#p21
p21_soupx <- CreateSeuratObject(counts = p21.data, project = "p21", min.cells = 3, min.features = 200)
p21_soupx[["percent.mt"]] <- PercentageFeatureSet(p21_soupx, pattern = "^MT-")
VlnPlot(p21_soupx, features = c("nFeature_RNA", "nCount_RNA"), ncol = 2)
featurescatterplot <- FeatureScatter(p21_soupx, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
plot(featurescatterplot)
p21_soupx <- subset(p21_soupx, subset = nFeature_RNA > 200 & nFeature_RNA < 4000)
p21_soupx <- NormalizeData(p21_soupx)
p21_soupx <- FindVariableFeatures(p21_soupx, selection.method = "vst", nfeatures = 2000)
top10 <- head(VariableFeatures(p21_soupx), 10)
plot1variable <- VariableFeaturePlot(p21_soupx)
plot2variable <- LabelPoints(plot = plot1variable, points = top10, repel = TRUE)
CombinePlots(plots = list(plot1variable, plot2variable))
all.genesp21 <- rownames(p21_soupx)
p21_soupx <- ScaleData(p21_soupx, features = all.genesp21)
p21_soupx <- RunPCA(p21_soupx, features = VariableFeatures(object = p21_soupx))
VizDimLoadings(p21_soupx, dims = 1:2, reduction = "pca")
DimPlot(p21_soupx, reduction = "pca")
DimHeatmap(p21_soupx, dims = 1:15, cells = 500, balanced = TRUE)
p21_soupx <- FindNeighbors(p21_soupx, dims = 1:15)
p21_soupx <- FindClusters(p21_soupx, resolution = 0.5)
p21_soupx <- RunUMAP(p21_soupx, dims = 1:15)
DimPlot(p21_soupx, reduction = "umap")
#Soleus
library(Seurat)
library(dplyr)
sol_soupx <- CreateSeuratObject(counts = sol_counts, project = "sol", min.cells = 3, min.features = 200)
VlnPlot(sol_soupx, features = c("nFeature_RNA", "nCount_RNA"), ncol = 2)
featurescatterplot <- FeatureScatter(sol_soupx, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
plot(featurescatterplot)
sol_soupx <- subset(sol_soupx, subset = nFeature_RNA > 200 & nFeature_RNA < 3200)
sol_soupx <- NormalizeData(sol_soupx)
sol_soupx <- FindVariableFeatures(sol_soupx, selection.method = "vst", nfeatures = 2000)
top10 <- head(VariableFeatures(sol_soupx), 10)
plot1variable <- VariableFeaturePlot(sol_soupx)
plot2variable <- LabelPoints(plot = plot1variable, points = top10, repel = TRUE)
CombinePlots(plots = list(plot1variable, plot2variable))
all.genes5mo <- rownames(sol_soupx)
sol_soupx <- ScaleData(sol_soupx, features = all.genes5mo)
sol_soupx <- RunPCA(sol_soupx, features = VariableFeatures(object = sol_soupx))
VizDimLoadings(sol_soupx, dims = 1:2, reduction = "pca")
DimPlot(sol_soupx, reduction = "pca")
DimHeatmap(sol_soupx, dims = 1:15, cells = 500, balanced = TRUE)
sol_soupx <- FindNeighbors(sol_soupx, dims = 1:20)
sol_soupx <- FindClusters(sol_soupx, resolution = 0.5)
sol_soupx <- RunUMAP(sol_soupx, dims = 1:20)
DimPlot(sol_soupx, reduction = "umap", label = TRUE)
sol_soupx <- RenameIdents(sol_soupx, '0' = "Type IIa Myonuclei", '1' = "FAPs", '2' = "Type IIx Myonuclei", '3' = "Type I Myonuclei", '4' = "Endothelial Cells", '5' = "Smooth Muscle", '6' = "Tenocytes", '7' = "Musculotendinous Junction", '8' = "Unidentified", '9' = "Smooth Muscle", '10' = "Unknown", '11' = "Satellite Cells", '12' = "FAPs", '13' = "Schwann Cells", '14' = "Neurons", "15" = "Unknown 2")
