fivemonth.data <- Read10X(data.dir = "D:/10X-datasets/10X_Millay_WT_Muscle/outs/mm10/filtered_feature_bc_matrix")
fivemonth <- CreateSeuratObject(counts = fivemonth.data, project = "A", min.cells = 3, min.features = 200)
fivemonth[["percent.mt"]] <- PercentageFeatureSet(fivemonth, pattern = "^MT-")

VlnPlot(fivemonth, features = c("nFeature_RNA", "nCount_RNA"), ncol = 2)
featurescatterplot <- FeatureScatter(fivemonth, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
plot(featurescatterplot)
fivemonth <- subset(fivemonth, subset = nFeature_RNA > 200 & nFeature_RNA < 3200)
fivemonth <- NormalizeData(fivemonth)
fivemonth <- FindVariableFeatures(fivemonth, selection.method = "vst", nfeatures = 2000)
top10 <- head(VariableFeatures(fivemonth), 10)
plot1variable <- VariableFeaturePlot(fivemonth)
plot2variable <- LabelPoints(plot = plot1variable, points = top10, repel = TRUE)
CombinePlots(plots = list(plot1variable, plot2variable))
all.genes5mo <- rownames(fivemonth)
fivemonth <- ScaleData(fivemonth, features = all.genes5mo)
fivemonth <- RunPCA(fivemonth, features = VariableFeatures(object = fivemonth))
VizDimLoadings(fivemonth, dims = 1:2, reduction = "pca")
DimPlot(fivemonth, reduction = "pca")
DimHeatmap(fivemonth, dims = 1:15, cells = 500, balanced = TRUE)
fivemonth <- FindNeighbors(fivemonth, dims = 1:12)
fivemonth <- FindClusters(fivemonth, resolution = 0.5)
fivemonth <- RunUMAP(fivemonth, dims = 1:12)
DimPlot(fivemonth, reduction = "umap", label = TRUE)
