library(Seurat)
p21_soupx <- CreateSeuratObject(counts = p21_counts, project = "p21", min.cells = 3, min.features = 200)
VlnPlot(p21_soupx, features = c("nFeature_RNA", "nCount_RNA"), ncol = 2)
featurescatterplot <- FeatureScatter(p21_soupx, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
plot(featurescatterplot)
p21_soupx <- subset(p21_soupx, subset = nFeature_RNA > 200 & nFeature_RNA < 4000)
p21_soupx <- NormalizeData(p21_soupx)
p21_soupx <- FindVariableFeatures(p21_soupx, selection.method = "vst", nfeatures = 2000)
top10 <- head(VariableFeatures(p21_soupx), 10)
plot1variable <- VariableFeaturePlot(p21_soupx)
plot2variable <- LabelPoints(plot = plot1variable, points = top10, repel = TRUE)
CombinePlots(plots = list(plot1variable, plot2variable))
all.genesp21 <- rownames(p21_soupx)
p21_soupx <- ScaleData(p21_soupx, features = all.genesp21)
p21_soupx <- RunPCA(p21_soupx, features = VariableFeatures(object = p21_soupx))
VizDimLoadings(p21_soupx, dims = 1:2, reduction = "pca")
DimPlot(p21_soupx, reduction = "pca")
DimHeatmap(p21_soupx, dims = 1:15, cells = 500, balanced = TRUE)
p21_soupx <- FindNeighbors(p21_soupx, dims = 1:15)
p21_soupx <- FindClusters(p21_soupx, resolution = 0.5)
p21_soupx <- RunUMAP(p21_soupx, dims = 1:15)
p21_soupx@reductions[["umap"]] <- p21_reductions
DimPlot(p21_soupx, reduction = "umap", label = TRUE)
p21_soupx <- RenameIdents(p21_soupx, "0" = "Nos1+ Myonuclei", "1" = "Type IIb Myonuclei", "2" = "Type IIx Myonuclei", "3" = "FAPs", "4" = "Endothelial Cells", "5" = "Smooth Muscle", "6" = "Enah+ Myonuclei", "7" = "FAPs #2", "8" = "Satellite Cells", "9" = "Type IIb Myonuclei #2", "10" = "Immune Cells", "11" = "Tenocytes", "12" = "Schwann Cells", "13" = "Neuromuscular Junction", "14" = "Myotendinous Junction", "15" = "Endothelial Cells #2")
DimPlot(p21_soupx, reduction = "umap", label = TRUE)
