library(Seurat)
library(dplyr)
thirty_soupx <- CreateSeuratObject(counts = thirtycounts, project = "thirtymonth", min.cells = 3, min.features = 200)
VlnPlot(thirty_soupx, features = c("nFeature_RNA", "nCount_RNA"), ncol = 2)
featurescatterplot <- FeatureScatter(thirty_soupx, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
plot(featurescatterplot)
thirty_soupx <- subset(thirty_soupx, subset = nFeature_RNA > 200 & nFeature_RNA < 4000)
thirty_soupx <- NormalizeData(thirty_soupx)
thirty_soupx <- FindVariableFeatures(thirty_soupx, selection.method = "vst", nfeatures = 2000)
top10 <- head(VariableFeatures(thirty_soupx), 10)
plot1variable <- VariableFeaturePlot(thirty_soupx)
plot2variable <- LabelPoints(plot = plot1variable, points = top10, repel = TRUE)
CombinePlots(plots = list(plot1variable, plot2variable))
all.genes5mo <- rownames(thirty_soupx)
thirty_soupx <- ScaleData(thirty_soupx, features = all.genes5mo)
thirty_soupx <- RunPCA(thirty_soupx, features = VariableFeatures(object = thirty_soupx))
VizDimLoadings(thirty_soupx, dims = 1:2, reduction = "pca")
DimPlot(thirty_soupx, reduction = "pca")
DimHeatmap(thirty_soupx, dims = 1:15, cells = 500, balanced = TRUE)
thirty_soupx <- FindNeighbors(thirty_soupx, dims = 1:20)
thirty_soupx <- FindClusters(thirty_soupx, resolution = 0.5)
thirty_soupx <- RunUMAP(thirty_soupx, dims = 1:20)
thirty_soupx@redctions[["umap"]] <- thirty_reductions
DimPlot(thirty_soupx, reduction = "umap", label = TRUE)
thirty_soupx <- RenameIdents(thirty_soupx, "0" = "Type IIb Myonuclei", "1" = "Type IIx Myonuclei", "2" = "Nr4a3+ Myonuclei", "3" = "FAPs", "4" = "Immune Cells", "5" = "Smooth Muscle", "6" = "Unnamed", "7" = "Enah+ Myonuclei", "8" = "Endothelial Cells", "9" = "Myotendinous Junction", "10" = "Ampd3+ Myonuclei", "11" = "Neuromuscular Junction", "12" = "Satellite Cells", "13" = "Tenocytes", "14" = "Smooth Muscle #2")
DimPlot(thirty_soupx, reduction = "umap", label = TRUE)
