library(Seurat)
library(dplyr)
twentyfour_soupx <- CreateSeuratObject(counts = twentyfourcounts, project = "B", min.cells = 3, min.features = 200)
VlnPlot(twentyfour_soupx, features = c("nFeature_RNA", "nCount_RNA"), ncol = 2)
featurescatterplot <- FeatureScatter(twentyfour_soupx, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
plot(featurescatterplot)
twentyfour_soupx <-  subset(twentyfour_soupx, subset = nFeature_RNA > 200 & nFeature_RNA < 4000) 
twentyfour_soupx <- NormalizeData(twentyfour_soupx)
twentyfour_soupx <- FindVariableFeatures(twentyfour_soupx, selection.method = "vst", nfeatures = 2000)
top10 <- head(VariableFeatures(twentyfour_soupx), 10)
plot1variable <- VariableFeaturePlot(twentyfour_soupx)
plot2variable <- LabelPoints(plot = plot1variable, points = top10, repel = TRUE)
CombinePlots(plots = list(plot1variable, plot2variable))
all.genes5mo <- rownames(twentyfour_soupx)
twentyfour_soupx <- ScaleData(twentyfour_soupx, features = all.genes5mo)
twentyfour_soupx <- RunPCA(twentyfour_soupx, features = VariableFeatures(object = twentyfour_soupx))
VizDimLoadings(twentyfour_soupx, dims = 1:2, reduction = "pca")
DimPlot(twentyfour_soupx, reduction = "pca")
DimHeatmap(twentyfour_soupx, dims = 1:15, cells = 500, balanced = TRUE)
twentyfour_soupx <- FindNeighbors(twentyfour_soupx, dims = 1:15)
twentyfour_soupx <- FindClusters(twentyfour_soupx, resolution = 0.5)
twentyfour_soupx <- RunUMAP(twentyfour_soupx, dims = 1:15)
twentyfour_soupx@reductions[["umap"]] <- twentyfour_reductions
DimPlot(twentyfour_soupx, reduction = "umap", label = TRUE)
twentyfour_soupx <- RenameIdents(twentyfour_soupx, "0" = "Type IIb Myonuclei", "1" = "Type IIx Myonuclei", "2" = "Type IIb Myonuclei #2", "3" = "Type IIx Myonuclei #2", "4" = "FAPs", "5" = "Smooth Muscle", "6" = "Endothelial Cells", "7" = "Myotendinous Junction", "8" = "Satellite Cells", "9" = "Immune Cells", "10" = "Smooth Muscle #2", "11" = "Endothelial Cells #2", "12" = "Neuromuscular Juncion", "13" = "Schwann Cells", "14" = "Adipocytes")
DimPlot(twentyfour_soupx, reduction = "umap", label = TRUE)
